# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site ## https://segmentfault.com/a/1190000007477815
# look at themes/next/languages
title: 小天地 
subtitle: 没有次标题
description: "这是我的博客,哈哈哈~"
keywords: xiaotiandi,ledong 
author: xiaotiandi
language: zh-Hans
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
# url: http://yoursite.com
# url: http://xiaotiandi.coding.me/publicBlog
url: https://xiaotiandi.github.io/publicBlog/
root: /publicBlog/
#permalink: :year/:month/:day/:title/
permalink: :year-:month-:day-:abbrlink.html
permalink_defaults:

## https://blog.csdn.net/panchao888888/article/details/80666352
abbrlink:  
  alg: crc32  # 算法：crc16(default) and crc32  
  rep: hex    # 进制：dec(default) and hex  


# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: ./ #表示从source目录开始
# code_dir: downloads/code
i18n_dir: :lang
skip_render:
    - README.md

# Writing
new_post_name: :title-ld:year:month:day.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true 
  line_number: true
  auto_detect: true
  tab_replace: true
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 20
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: landscape
theme: hexo-theme-next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
## https://www.zhihu.com/question/21193762
## https://github.com/hexojs/hexo-deployer-git
deploy:
  - type: git
    repository: git@github.com:xiaotiandi/publicBlog.git
    branch: master
  - type: git
    repository: git@git.coding.net:xiaotiandi/publicBlog.git
    branch: master
  - type: git
    repository: git@git.coding.net:xiaotiandi/publicBlog.git
    branch: hexo
    extend_dirs: /
    ignore_hidden: false
    ignore_pattern: 
      public: .
      /: .deploy_git

############################
## plugins
## https://chriszheng.science/2015/11/08/Checkbox-for-markdown-mode/

plugins: markdown-it-checkbox

## https://github.com/CHENXCHEN/hexo-renderer-markdown-it-plus
markdown_it_plus:
    highlight: true
    html: true
    xhtmlOut: true
    breaks: true
    langPrefix:
    linkify: true
    typographer:
    quotes: “”‘’"'
    pre_class: highlight
    plugins:
          - plugin:
              name: markdown-it-mark
              enable: true 
          - plugin:
              name: markdown-it-checkbox
              enable: true        

search:
  path: search.xml
  field: post
  format: html
  limit: 100000  

## https://github.com/tea3/hexo-include-markdown
include_markdown:
  dir: source/_posts  # Base directory of template markdown
  verbose : true       # If you want to check the path of markdown that use <!-- md --> tag , please set the true.

